# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchhg }:

super: rec {
  "Pillow" = super.buildPythonPackage rec {
    pname = "Pillow";
    version = "10.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/89/818fa238e37a47a29bb8495ca2cafdd514599a89f19ada7916348a74b5f9/Pillow-10.0.0-cp311-cp311-manylinux_2_28_x86_64.whl";
      sha256 = "cd25d2a9d2b36fcb318882481367956d2cf91329f6892fe5d385c346c0649629";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      pkgs.gcc12
    ];
  };
  "bCNC" = super.buildPythonPackage rec {
    pname = "bCNC";
    version = "0.9.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/be/4a49fa0b2e89ccaad0da8bd14f5dffe492c9de6b1c8c4524b0ca1234bf5b/bCNC-0.9.15.tar.gz";
      sha256 = "1wsz5ppgncn992znj9wpkvjkf87m93zb2pdzlas53nnj2j4pz9vw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      Pillow
      numpy
      opencv-python
      pyserial
      shxparser
      svgelements
      pkgs.python311Packages.tkinter
    ];
  };
  "numpy" = super.buildPythonPackage rec {
    pname = "numpy";
    version = "1.25.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cf/7a/f68d1d658a0e68084097beb212fa9356fee7eabff8b57231cc4acb555b12/numpy-1.25.1.tar.gz";
      sha256 = "9a3a9f3a61480cc086117b426a8bd86869c213fc4072e606f01c4e4b66eb92bf";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      pkgs.python311Packages.cython
    ];
  };
  "opencv-python" = super.buildPythonPackage rec {
    pname = "opencv-python";
    version = "4.5.5.62";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/98/36bfcbff30da27dd6922ed73ca7802c37d87f77daf4c569da3dcb87b4296/opencv_python-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "130cc75d56b29aa3c5de8b6ac438242dd2574ba6eaa8bccdffdcfd6b78632f7f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      numpy
    ];
  };
  "pyserial" = super.buildPythonPackage rec {
    pname = "pyserial";
    version = "3.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl";
      sha256 = "1w1c5z0gxvjcl73n828pvrfwb9b7mrxyrcwz575ac71rpav1sif4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "shxparser" = super.buildPythonPackage rec {
    pname = "shxparser";
    version = "0.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/fb/98c8204a5348566f24ee23127a680a9b5ddd3614ecc5a00a4efe4d5f53e4/shxparser-0.0.2-py2.py3-none-any.whl";
      sha256 = "0v3svf0ggw37a8bi4k0yng3kxchdm7a5igw926b8q3s4cffprlyc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "svgelements" = super.buildPythonPackage rec {
    pname = "svgelements";
    version = "1.9.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/f3/a0ebf07abf842d309207cba39af08ac572f158c1a1fa0024d92125a7e55f/svgelements-1.9.5-py2.py3-none-any.whl";
      sha256 = "1zr8mg8nyi0m15a7bb4fd49aavrkaqw95nm4csfv2zk299487d9j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
