#!/usr/bin/env bash

declare -A workspaces
focused_workspace=$(hyprctl -j activeworkspace | jaq -j '.id')

load_workspaces() {
    while read -r k v; do workspaces[$k]=$v; done < <(hyprctl -j workspaces | jaq -jr '.[] | .id, " ", .windows, "\n"')
}

json_workspaces_eww() {
    echo -n '{"workspaces":['
    for workspace in {1..9}; do
        [ $workspace -eq 9 ] && separator="" || separator=","
        [ $focused_workspace -eq $workspace ] && focused=true || focused=false
        [[ ${workspaces[$workspace]} -ne "" ]] && [ ${workspaces[$workspace]} -gt 0 ] && fill=true || fill=false

        printf "%s%s" "{\"id\":$workspace,\"focus\":$focused,\"fill\":$fill}" $separator
    done
    echo ']}'
}

load_workspaces

json_workspaces_eww

socat -u unix-connect:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | rg --line-buffered "workspace|window" | while read -r line; do
    data=${line#*>>}
    case ${line%>>*} in
        workspace)
            printf "%s\n" $data >&2
            focused_workspace=$data
	    ;;
	createworkspace)
            ;;
        destroyworkspace)
            workspaces[$data]=""
            ;;
        moveworkspace)
            ;;
        *window)
	    load_workspaces
	    ;;
        windowtitle)
            ;;
    esac
    json_workspaces_eww
done

